// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {indentation} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "bOQOQOOOOOO'#C^'#C^QOOOOO",
  stateData: "V~OVPO~O",
  goto: "VRPPSRQO",
  nodeNames: "⚠ Model Name",
  maxTerm: 7,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "m~RQ!c!}X#T#oX~^TV~}!OX!Q![X!c!}X#R#SX#T#oX",
  tokenizers: [indentation, 0],
  topRules: {"Model":[0,1]},
  tokenPrec: 0
})
