// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {indentation, trackIndent} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQQOPOOOOOQ'#C_'#C_OOOO'#Ca'#CaQQOPOOOVOQO'#C^OOOO-E6_-E6_OQOPO,58xOOOO'#C`'#C`OOOO1G.d1G.d",
  stateData: "[~OYPO~OVUO~O",
  goto: "kUPPVZbeTQORSSORRVURWUQRORTR",
  nodeNames: "⚠ root Model Name Field",
  maxTerm: 10,
  context: trackIndent,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "m~RQ!c!}X#T#oX~^TY~}!OX!Q![X!c!}X#R#SX#T#oX",
  tokenizers: [0, indentation],
  topRules: {"root":[0,1]},
  tokenPrec: 0
})
