// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 17,
  redent = 18,
  dedent = 19,
  root = 1,
  Model = 2,
  Name = 3,
  Field = 4,
  Type = 5,
  TypeSymbol = 6,
  TypeEnumVariant = 7,
  UnionType = 8,
  ArrayOfType = 9,
  FieldChild = 10
